name: HamGift
main: org.hamgift.main.Main
version: 1.0

commands:
  hgift:
    description: The command of HamGift

  hg:
    description: The command of HamGift

permissions:
  hgift.*:
    description: The permission about hgifts.
    children:
      hgift.get: true
      hgift.set: false

  hgift.get:
    description: Allows to get hgifts.
    default: true

  hgift.set:
    description: Allows to set hgifts
    default: op